#!/bin/sh
### This file should only contain hardware initalization commands that will only fail if the hardware is
##  bad. Anything that we can limp along without should be put somewhere else so that this script exits
##  with status 0 and the system init process can continue.

mkdir -p /dev/socket
chown anki:anki /dev/socket

# @nathan-anki  - to stop overheating, limit CPU to 533MHz, RAM to 400MHz
# this is now handled by wired, theoretically
echo 533333 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
# actually 400
echo 200000 > /sys/bus/platform/devices/400000.interconnect/bus_scaling/scaling_max_rate_khz
#End clock speed limits

# emr-cat prints a placeholder value even on error
SERIALNO=`/bin/emr-cat e`
HAVE_EMR=$?

# And put the serial number in properties
for i in `seq 1 5`;
do
    setprop ro.serialno $SERIALNO
    if test ! -z `getprop ro.serialno`; then break; fi
    sleep 1;
done

# Put the model into a property
setprop ro.hw.ver `/bin/emr-cat v`
setprop ro.model `/bin/emr-cat m`

if [ -x /usr/bin/vic-christen ]; then
    /usr/bin/vic-christen
fi

/bin/hostname `getprop anki.robot.name | tr ' ' '-'`

# If we are coming up from a maintenance reboot, let the anki apps know
if [ -e /data/maintenance_reboot ]; then
    mv /data/maintenance_reboot /run/after_maintenance_reboot
fi

# Report OS Version to boot log
echo "VicOS Version: `getprop ro.anki.version`" > /dev/kmsg

# camera

SENSOR=""
RES=""
if [ $(emr-cat v) == "00000020" ]; then
	modprobe bf2253l
	SENSOR="bf2253l 0-006e"
	RES="1600x1200"
else
 	modprobe gc1066
	SENSOR="gc1066 0-003c"
	RES="1280x720"
fi
sleep 1

media-ctl --links '"'"$SENSOR"'":0 -> "msm_csiphy0":0 [1], "msm_csiphy0":1 -> "msm_csid0":0 [1], "msm_csid0":1 -> "msm_ispif0":0 [1], "msm_ispif0":1 -> "msm_vfe0_rdi0":0 [1]'

media-ctl --set-v4l2 "'$SENSOR':0[fmt:SBGGR10_1X10/${RES}]"
media-ctl --set-v4l2 "'msm_csiphy0':0[fmt:SBGGR10_1X10/${RES}]"                                                                                             
media-ctl --set-v4l2 "'msm_csiphy0':1[fmt:SBGGR10_1X10/${RES}]"
media-ctl --set-v4l2 "'msm_csid0':0[fmt:SBGGR10_1X10/${RES}]"
media-ctl --set-v4l2 "'msm_csid0':1[fmt:SBGGR10_1X10/${RES}]"
media-ctl --set-v4l2 "'msm_ispif0':0[fmt:SBGGR10_1X10/${RES}]"
media-ctl --set-v4l2 "'msm_ispif0':1[fmt:SBGGR10_1X10/${RES}]"
media-ctl --set-v4l2 "'msm_vfe0_rdi0':0[fmt:SBGGR10_1X10/${RES}]"
media-ctl --set-v4l2 "'msm_vfe0_rdi0':1[fmt:SBGGR10_1X10/${RES}]"

# usb

mount -t configfs none /sys/kernel/config 2>/dev/null || true
cd /sys/kernel/config/usb_gadget
mkdir -p g1
cd g1
echo 0x18d1 > idVendor
echo 0x4ee8 > idProduct
mkdir -p strings/0x409
echo "Anki"   > strings/0x409/manufacturer
echo "Vector" > strings/0x409/product
echo "0002"   > strings/0x409/serialnumber
mkdir -p configs/c.1/strings/0x409
echo "ecm" > configs/c.1/strings/0x409/configuration
mkdir -p functions/ecm.usb0
echo 02:00:00:00:00:01 > functions/ecm.usb0/dev_addr
echo 02:00:00:00:00:02 > functions/ecm.usb0/host_addr
ln -s functions/ecm.usb0 configs/c.1/
echo ci_hdrc.0 > UDC

# wlan

echo start > /sys/class/remoteproc/remoteproc1/state

exit 0
