#!/bin/sh

echo "anki-audio-init: START" > /dev/kmsg

# wait for /sys/class/sound/card0 to appear
# indicating that the alsa driver has detected our sound system

MAX_RETRIES=120 # 60 sec
COUNT=0
while [ ! -e /sys/class/sound/card0 ]
do
  sleep 0.5
  COUNT=$((COUNT+1))
  if [ $COUNT -ge $MAX_RETRIES ]; then
    exit 1
  fi
done

amixer cset name='PRI_MI2S_RX Audio Mixer MultiMedia1' 1                                                      
amixer cset name='RX3 MIX1 INP1' 'RX1'                                                                  
amixer cset name='SPK DAC Switch' 1                                                                           
amixer cset name='RX3 Digital Volume' 70
amixer cset name='RX3 Mute Switch' 0
