#!/bin/sh
### This file should only contain hardware initalization commands that will only fail if the hardware is
##  bad. Anything that we can limp along without should be put somewhere else so that this script exits
##  with status 0 and the system init process can continue.

# @nathan-anki  - to stop overheating, limit CPU to 533MHz, RAM to 400MHz
# this is now handled by wired, theoretically
echo 533333 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
#End clock speed limits

# Move RT FIFO tasks off core 0 to reduce timer interrupt induced jitter.
pgrep tty | xargs -I PID taskset -p 0xe PID

# # TODO Move this power rail controll into the camera driver
# CAM_REG_GPIO=83
# if [ ! -d /sys/class/gpio/gpio$CAM_REG_GPIO ]; then
#     echo $CAM_REG_GPIO > /sys/class/gpio/export
# fi
# echo out > /sys/class/gpio/gpio$CAM_REG_GPIO/direction
# echo 1 > /sys/class/gpio/gpio$CAM_REG_GPIO/value
# End camera force hack

# Set spi buf size to size of LCD frame (184*96*2)
chmod 666 /sys/module/spidev/parameters/bufsiz
echo 35328 > /sys/module/spidev/parameters/bufsiz
chmod 444 /sys/module/spidev/parameters/bufsiz

# emr-cat prints a placeholder value even on error
SERIALNO=`/bin/emr-cat e`
HAVE_EMR=$?

# And put the serial number in properties
for i in `seq 1 5`;
do
    setprop ro.serialno $SERIALNO
    if test ! -z `getprop ro.serialno`; then break; fi
    sleep 1;
done

# Put the model into a property
setprop ro.hw.ver `/bin/emr-cat v`
setprop ro.model `/bin/emr-cat m`

if [ -x /usr/bin/vic-christen ]; then
    /usr/bin/vic-christen
fi

/bin/hostname `getprop anki.robot.name | tr ' ' '-'`

# If we are coming up from a maintenance reboot, let the anki apps know
if [ -e /data/maintenance_reboot ]; then
    mv /data/maintenance_reboot /run/after_maintenance_reboot
fi

#Enable Ramoops
#modprobe ramoops

# Report OS Version to boot log
echo "VicOS Version: `getprop ro.anki.version`" > /dev/kmsg

# usb

mount -t configfs none /sys/kernel/config 2>/dev/null || true
cd /sys/kernel/config/usb_gadget
mkdir -p g1
cd g1
echo 0x18d1 > idVendor
echo 0x4ee8 > idProduct
mkdir -p strings/0x409
echo "anki"   > strings/0x409/manufacturer
echo "vector" > strings/0x409/product
echo "0002"   > strings/0x409/serialnumber
mkdir -p configs/c.1/strings/0x409
echo "ecm" > configs/c.1/strings/0x409/configuration
mkdir -p functions/ecm.usb0
echo 02:00:00:00:00:01 > functions/ecm.usb0/dev_addr
echo 02:00:00:00:00:02 > functions/ecm.usb0/host_addr
ln -s functions/ecm.usb0 configs/c.1/
echo ci_hdrc.0 > UDC
ip addr add 192.168.7.2/24 dev usb0
ip link set usb0 up

# wlan

echo start > /sys/class/remoteproc/remoteproc1/state

exit 0
