#! /bin/sh

# Copyright (c) 2017, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#   * Neither the name of The Linux Foundation nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

UNBRICK_KEY="anki.unbrick"
WIPE_COOKIE="/run/wipe-data"
TOM_LOG="/factory/log1"
ROBOT_KEY=/data/etc/robot.pem
USER_DATA_PARTITION=/dev/block/bootdevice/by-name/userdata
MOUNT_OPTIONS="defaults,exec,nosuid,nodev,noatime"

make_and_mount_cryptdata() {
  echo "Remaking /data" > /dev/kmsg
  # we no longer need these options for mainline, but it's
  # probably best to keep compatibility with the older kernel
  mkfs.ext4 -O ^metadata_csum,^64bit $USER_DATA_PARTITION
  mount -o $MOUNT_OPTIONS $USER_DATA_PARTITION /data
}

make_userdata() {
  mkdir -p /data/lib/connman/
  cp -rf /var/lib/connman/* /data/lib/connman
  if [ ! -f $ROBOT_KEY ]; then
    mkdir -p /data/etc
    openssl genrsa -out $ROBOT_KEY 2048
    chown net:anki $ROBOT_KEY
    chmod 440 $ROBOT_KEY
  fi

  #usb
  mkdir -p /data/usb
  #camera
  mkdir -p /data/misc/camera
  #data
  mkdir -p /data/data/com.anki.victor
  chown -R anki:anki /data/data/com.anki.victor
  chmod -R 770 /data/data/com.anki.victor
  #vic-gateway
  mkdir -p /data/vic-gateway
  chown -R net:anki /data/vic-gateway
  chmod -R 770 /data/vic-gateway
  #bluetooth
  mkdir -p /data/misc/bluetooth
  chown -R bluetooth:bluetooth /data/misc/bluetooth
  chmod -R 770 /data/misc/bluetooth
  #panics
  mkdir -p /data/panics
  chown -R anki:anki /data/panics
  chmod -R 770 /data/panics

  #make sure /data/run/connman exists - NOTE: we need /data/lib/connman and /data/run/connamn
  mkdir -p /data/run/connman
}

mount_tmp_userdata() {
  mount -o size=64M -t tmpfs none /data/
  rc=$?
  return $rc
}

mount_userdata() {
    # Try to mount the /data partition
    mount -o $MOUNT_OPTIONS $USER_DATA_PARTITION /data
    rc=$?
    if [ $rc -ne 0 ]; then
      echo "mount /data returned $rc"
    fi
    return $rc
}


case "$1" in
  start )
    mount_userdata
    mounted=$?
    if [ $mounted -ne 0 ]; then
      make_and_mount_cryptdata
      mounted=$?
      sync
      if [ $mounted -eq 0 ]; then
        dmesg > /data/format-data.log
        echo "-----------------------------" >> /data/format-data.log
        journalctl -u mount-data >> /data/format-data.log
      fi
    fi
    rm -rf $KEY_FILE

    # Always create userdata
    make_userdata

    # Set up our strange time zone solution
    mkdir -p /data/etc

    if [[ ! -f /data/etc/localtime ]]; then
      cp /usr/share/zoneinfo/America/Chicago /data/etc/localtime
    fi
    if [[ ! -f /data/etc/timezone ]]; then
      echo "America/Chicago" > /data/etc/timezone
    fi
    mount --bind /data/etc/localtime /etc/localtime
    mount --bind /data/etc/timezone  /etc/timezone
    ;;

  stop )
    echo "Unmounting /data"
    sync
    umount /data
    if test -e $WIPE_COOKIE; then
      blkdiscard -s $USER_DATA_PARTITION
      blkdiscard -s /dev/block/bootdevice/by-name/switchboard
      echo WIPE > /dev/block/bootdevice/by-name/userdata
    fi
    ;;

  * )
    echo "Usage: mount-data { start | stop }"
    ;;
esac

exit 0
