# Is this a bad idea?
name: Build Viccyware DEV ota

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to build'
        required: true
        default: 'Viccyware-tester'
  push:
    tags:
      - 'v*'  

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        submodules: recursive
        fetch-depth: 0
    
    - name: Run Build Script
      run: |
        ./build/build.sh -bt dev -v 5
    
    - name: Upload ota
      uses: actions/upload-artifact@v4
      with:
        name: ota-artifacts-${{ github.ref_name }}
        path: _build/*.ota
        retention-days: 30
        if-no-files-found: warn
