# Is this a bad idea?
name: Build Viccyware otas

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or Tag to build'
        required: true
        default: 'Viccyware-tester'
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Determine Checkout Ref
      id: get-ref
      run: |
        if [ -n "${{ github.event.inputs.ref }}" ]; then
          echo "ref=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ github.ref_name }}" ]; then
          echo "ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
          echo "ref=Viccyware-tester" >> $GITHUB_OUTPUT
        fi
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.get-ref.outputs.ref }}
        submodules: recursive
        fetch-depth: 0
    
    - name: Modify Build Script to Remove TTY Requirement
      run: |
        sed -i 's/docker run -it/docker run -i/' build/build.sh
    
    - name: Run Build Script
      run: |
        chmod +x build/build.sh
        ./build/build.sh -bt dev -v 1
        ./build/build.sh -bt oskr -bp annul-burl-zq-flew-hack-owe-phil-triton-pk -v 1
    
    - name: Upload otas to github
      uses: actions/upload-artifact@v4
      with:
        name: ota-artifacts-${{ steps.get-ref.outputs.ref }}
        path: _build/*.ota
        retention-days: 30
        if-no-files-found: warn
